# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main, master, dev*, feature* ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        python -m spacy download en_core_web_sm
        pip install -e .

    - name: Create test data directories
      run: |
        mkdir -p tests/data/images
        mkdir -p tests/data/videos

    - name: Download test images
      run: |
        # Download sample images for testing
        wget -P tests/data/images https://raw.githubusercontent.com/ultralytics/yolov5/master/data/images/bus.jpg -O tests/data/images/street.jpg
        wget -P tests/data/images https://raw.githubusercontent.com/ultralytics/yolov5/master/data/images/zidane.jpg -O tests/data/images/person.jpg

    - name: Download test video
      run: |
        # Download sample video for testing
        wget -P tests/data/videos https://raw.githubusercontent.com/ultralytics/yolov5/master/data/videos/human-cropped.mp4 -O tests/data/videos/crosswalk.avi

    - name: Run tests with pytest
      run: |
        pytest tests/ --cov=vision_framework --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8 mypy

    - name: Run linting
      run: |
        black --check vision_framework tests
        isort --check-only vision_framework tests
        flake8 vision_framework tests

  build:
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build wheel

    - name: Build package
      run: |
        python -m build

    - name: Upload package artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/
